name: Laravel

on:
  push:
  pull_request:

env:
  DB_USERNAME: sail
  DB_PASSWORD: password
  MAIL_FROM_ADDRESS: info@example.com

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql.test:
        image: "mysql/mysql-server:8.0"
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: "example_app"
          MYSQL_USER: ${{ env.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
